[build] Add D-Bus cflags to build, depend on ConnMan 1.37.  JB#51243
ConnMan 1.37 changes the headers so D-Bus became a dependency because
of:
 - device.h includes network.h
 - network.h was added dbus/dbus.h as an include
 -> /usr/include/connman/network.h:28:10: fatal error: dbus/dbus.h:
    No such file or directory

Add cflags to include D-Bus and set ConnMan 1.37 as a requirement for
the build. connman-devel has the BuildRequirement set tof D-Bus.